#!/usr/bin/env python3
"""Register the Coolify Microsoft provider and save credentials without printing them."""

from datetime import datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
from urllib.parse import urlencode


APP_NAME = "Enterprise App Coolify"
AUDIENCE = "AzureADandPersonalMicrosoftAccount"
REDIRECT_URI = (
    "https://ent-app-auth.portfolio-projects.dev/realms/enterprise-app"
    "/broker/microsoft/endpoint"
)
GRAPH = "https://graph.microsoft.com/v1.0"
# Published Microsoft Graph identifiers, not deployment credentials.
GRAPH_APP_ID = "00000003-0000-0000-c000-000000000000"
USER_READ_SCOPE = "e1fe6dd8-ba31-4d61-89e7-88639da4683d"
ENV_KEYS = ("MICROSOFT_CLIENT_ID", "MICROSOFT_CLIENT_SECRET")


def graph(method: str, path: str, operation: str, body: dict | None = None):
    """Call Graph using the current Azure CLI session; suppress credential output."""
    command = [
        "az", "rest", "--method", method, "--url", f"{GRAPH}/{path}",
        "--output", "json", "--only-show-errors",
    ]
    if body is not None:
        # Request bodies contain configuration only. Secrets are generated by Graph.
        command += ["--body", json.dumps(body)]
    result = subprocess.run(command, capture_output=True, text=True, check=False)
    if result.returncode:
        detail = "Azure CLI response suppressed to protect credentials."
        if "Authorization_RequestDenied" in result.stderr:
            detail = "Microsoft denied permission (Authorization_RequestDenied)."
        elif "az login" in result.stderr:
            detail = "Authenticate with az login in Default Directory first."
        raise RuntimeError(f"{operation} failed. {detail}")
    return json.loads(result.stdout) if result.stdout.strip() else None


def microsoft_values(text: str) -> dict[str, str]:
    """Read only the provider fields; reject duplicate assignments."""
    values = {}
    for line in text.splitlines():
        key, separator, value = line.partition("=")
        key = key.strip()
        if separator and key in ENV_KEYS:
            if key in values:
                raise RuntimeError(f"Duplicate {key} in .env; no values changed.")
            values[key] = value.strip().strip("\"'")
    return values


def verify_application(app: dict) -> None:
    """Require the dedicated registration to match this provider's configuration."""
    expected_access = [{
        "resourceAppId": GRAPH_APP_ID,
        "resourceAccess": [{"id": USER_READ_SCOPE, "type": "Scope"}],
    }]
    if (
        app.get("displayName") != APP_NAME
        or app.get("signInAudience") != AUDIENCE
        or app.get("web", {}).get("redirectUris") != [REDIRECT_URI]
        or app.get("requiredResourceAccess") != expected_access
        or app.get("api", {}).get("requestedAccessTokenVersion") != 2
    ):
        raise RuntimeError(
            "The existing dedicated registration has different settings; "
            "it was preserved. Review Enterprise App Coolify in Default Directory."
        )


def main() -> None:
    """Create once, reuse matching configuration, and preserve existing local values."""
    directory = Path(__file__).resolve().parent
    destination = directory / ".env"
    if not destination.is_file():
        raise RuntimeError("Run deploy/coolify/init-env.py first.")
    ignored = subprocess.run(
        ["git", "check-ignore", "-q", str(destination)], cwd=directory,
        capture_output=True, check=False,
    )
    if ignored.returncode:
        raise RuntimeError("The local .env must be ignored by Git before setup.")
    if any(microsoft_values(destination.read_text()).values()):
        print("Existing Microsoft fields preserved; no provider changes made.")
        return
    destination.chmod(0o600)

    organizations = graph(
        "GET", "organization?$select=displayName,tenantType", "Directory check"
    )["value"]
    if (
        len(organizations) != 1
        or organizations[0].get("displayName") != "Default Directory"
        or organizations[0].get("tenantType") != "AAD"
    ):
        raise RuntimeError("Select Default Directory (AAD) in Azure CLI first.")

    query = urlencode({"$filter": f"displayName eq '{APP_NAME}'"})
    matches = graph("GET", f"applications?{query}", "Registration lookup")["value"]
    if len(matches) > 1:
        raise RuntimeError("Multiple Enterprise App Coolify registrations found; preserved all.")
    if matches:
        app = matches[0]
        verify_application(app)
        print("Reusing matching Enterprise App Coolify registration.")
    else:
        app = graph("POST", "applications", "Registration creation", {
            "displayName": APP_NAME,
            "signInAudience": AUDIENCE,
            "api": {"requestedAccessTokenVersion": 2},
            "web": {
                "redirectUris": [REDIRECT_URI],
                "implicitGrantSettings": {
                    "enableAccessTokenIssuance": False,
                    "enableIdTokenIssuance": False,
                },
            },
            "requiredResourceAccess": [{
                "resourceAppId": GRAPH_APP_ID,
                "resourceAccess": [{"id": USER_READ_SCOPE, "type": "Scope"}],
            }],
        })
        print("Created Enterprise App Coolify in Default Directory.")

    expiry = datetime.now(timezone.utc) + timedelta(days=365)
    credential = graph("POST", f"applications/{app['id']}/addPassword", "Credential creation", {
        "passwordCredential": {
            "displayName": "Coolify Keycloak",
            "endDateTime": expiry.isoformat(timespec="seconds"),
        }
    })
    # addPassword appends a new secret; it never resets existing credentials.
    values = dict(zip(ENV_KEYS, (app["appId"], credential["secretText"])))
    current = destination.read_text()
    if any(microsoft_values(current).values()):
        raise RuntimeError("Microsoft fields changed during setup; existing local values preserved.")
    lines = current.splitlines()
    for key, value in values.items():
        # Keep simple credentials directly copyable into Coolify value fields.
        # Quote only when dotenv syntax requires it.
        if re.fullmatch(r"[A-Za-z0-9._~-]+", value):
            replacement = f"{key}={value}"
        else:
            escaped = value.replace("\\", "\\\\").replace("'", "\\'")
            replacement = f"{key}='{escaped}'"
        indexes = [i for i, line in enumerate(lines) if line.partition("=")[0].strip() == key]
        if indexes:
            lines[indexes[0]] = replacement
        else:
            lines.append(replacement)
    # A temporary .env is also Git-ignored; replace atomically with mode 0600.
    with tempfile.TemporaryDirectory(dir=directory) as temporary:
        staged = Path(temporary) / ".env"
        descriptor = os.open(staged, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(descriptor, "w") as output:
            output.write("\n".join(lines) + "\n")
        os.replace(staged, destination)

    verified = graph("GET", f"applications/{app['id']}", "Registration verification")
    verify_application(verified)
    print("Verified Microsoft/personal account audience, broker callback, and delegated User.Read.")
    print("Saved both Microsoft fields to ignored deploy/coolify/.env (mode 0600).")
    print(f"Client secret expires {credential['endDateTime']}; existing credentials were preserved.")


if __name__ == "__main__":
    try:
        main()
    except (OSError, RuntimeError, KeyError, ValueError) as error:
        raise SystemExit(str(error)) from None
