name: enterprise-app

services:
  ea-api:
    volumes:
      - ../api/src:/src
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  ea-ui:
    image: node:22-alpine
    build: !reset null
    working_dir: /app
    command: npm run dev
    volumes:
      - ../ui:/app
      - ui-node-modules:/app/node_modules
    ports:
      - "3000:3000"

volumes:
  ui-node-modules:
